// export { aes } from './lib/aes'
// export { timelapse } from './lib/timelapse'
// export { axisTicks } from './lib/axis'
export { timer, elapsed } from './lib/timer'
// export { default as Chart } from './chart/Chart.svelte'
// export { default as Axis } from './chart/Axis.svelte'
export { default as Swatch } from './chart/Swatch.svelte'
// export { default as AxisTicks } from './chart/AxisTicks.svelte'
// export { default as AxisGrid } from './chart/AxisGrid.svelte'
// export { default as AxisLabels } from './chart/AxisLabels.svelte'
export { default as BarPlot } from './plots/BarPlot.svelte'
export { default as LinePlot } from './plots/LinePlot.svelte'
export { default as BoxPlot } from './plots/BoxPlot.svelte'
export { default as ViolinPlot } from './plots/ViolinPlot.svelte'
export { default as ScatterPlot } from './plots/old_ScatterPlot.svelte'
export * from './components/lib'
