---
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
trailingComma: none
overrides:
  - files: '*.html'
    options:
      useTabs: false
      parser: html
  - files: '*.css'
    options:
      useTabs: false
      parser: css
  - files: '*.scss'
    options:
      useTabs: false
      parser: scss
  - files:
      - '*.md'
    options:
      useTabs: false
      parser: markdown
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      useTabs: false
      parser: yaml
  - files:
      - '*.sql'
      - '*.ddl'
    options:
      useTabs: false
  - files:
      - '*.json'
    options:
      useTabs: false
      parser: json
  - files: '*.svelte'
    options:
      parser: svelte
  - files: '*.ts'
    options:
      parser: typescript
plugins:
  - prettier-plugin-svelte
