import { describe, it, expect } from 'vitest'
import { get } from 'svelte/store'
import { createNavigator } from '../src/navigation'

describe('list-navigation', () => {
	const items = Array.from({ length: 10 }, (_, i) => i + 1)

	it('should create a store for navigation', () => {
		const store = createNavigator(items)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 9 })
		expect(store).toHaveProperty('next')
		expect(store).toHaveProperty('previous')
		expect(store).toHaveProperty('first')
		expect(store).toHaveProperty('last')
		expect(store).toHaveProperty('select')
		expect(store).toHaveProperty('moveByOffset')
		expect(store).toHaveProperty('selectByIndex')
		expect(store).toHaveProperty('subscribe')
		expect(store).not.toHaveProperty('set')
		expect(store).not.toHaveProperty('update')
	})

	it('should move position by offset', () => {
		const store = createNavigator(items)
		store.moveByOffset(1)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
		store.moveByOffset(-1)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
		store.moveByOffset(5)
		expect(get(store)).toEqual({ index: 5, value: 6, start: 0, end: 9 })
		store.moveByOffset(15)
		expect(get(store)).toEqual({ index: 9, value: 10, start: 0, end: 9 })
		store.moveByOffset(-6)
		expect(get(store)).toEqual({ index: 3, value: 4, start: 0, end: 9 })
		store.moveByOffset(-15)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
	})

	it('should move to next item', () => {
		const store = createNavigator(items)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 9 })
		store.next()
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
		store.next()
		expect(get(store)).toEqual({ index: 1, value: 2, start: 0, end: 9 })
	})

	it('should move to previous item', () => {
		const store = createNavigator(items)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 9 })
		store.previous()
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
		store.next()
		expect(get(store)).toEqual({ index: 1, value: 2, start: 0, end: 9 })
		store.previous()
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
	})
	it('should move to first item', () => {
		const store = createNavigator(items)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 9 })
		store.first()
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
		store.moveByOffset(5)
		expect(get(store)).toEqual({ index: 5, value: 6, start: 0, end: 9 })
		store.first()
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
	})

	it('should move to last item', () => {
		const store = createNavigator(items)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 9 })
		store.last()
		expect(get(store)).toEqual({ index: 9, value: 10, start: 0, end: 9 })
		store.moveByOffset(-5)
		expect(get(store)).toEqual({ index: 4, value: 5, start: 0, end: 9 })
		store.last()
		expect(get(store)).toEqual({ index: 9, value: 10, start: 0, end: 9 })
	})

	it('should select item by value', () => {
		const store = createNavigator(items)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 9 })
		store.select(5)
		expect(get(store)).toEqual({ index: 4, value: 5, start: 0, end: 9 })
		store.select(15)
		expect(get(store)).toEqual({ index: 4, value: 5, start: 0, end: 9 })
		store.select(-5)
		expect(get(store)).toEqual({ index: 4, value: 5, start: 0, end: 9 })
	})

	it('should select item by index', () => {
		const store = createNavigator(items)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 9 })
		store.select(5)
		expect(get(store)).toEqual({ index: 4, value: 5, start: 0, end: 9 })
		store.select(15)
		expect(get(store)).toEqual({ index: 4, value: 5, start: 0, end: 9 })
		store.select(-5)
		expect(get(store)).toEqual({ index: 4, value: 5, start: 0, end: 9 })
	})

	it('should adjust subset range based on position change', () => {
		const store = createNavigator(items, 5)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 4 })
		store.next()
		store.moveByOffset(5)
		expect(get(store)).toEqual({ index: 5, value: 6, start: 1, end: 5 })
		store.next()
		expect(get(store)).toEqual({ index: 6, value: 7, start: 2, end: 6 })
		store.previous()
		expect(get(store)).toEqual({ index: 5, value: 6, start: 2, end: 6 })
		store.moveByOffset(-3)
		expect(get(store)).toEqual({ index: 2, value: 3, start: 2, end: 6 })
		store.previous()
		expect(get(store)).toEqual({ index: 1, value: 2, start: 1, end: 5 })
	})

	it('should adjust subset range when start is changed', () => {
		const store = createNavigator(items, 5)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 4 })
		store.next()
		store.setStart(1)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 1, end: 5 })
		store.setStart(8)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 5, end: 9 })
	})

	it('should adjust subset range when count is changed', () => {
		const store = createNavigator(items, 5)
		expect(get(store)).toEqual({ index: -1, value: null, start: 0, end: 4 })
		store.next()
		store.setSubset(3)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 2 })
		store.setSubset(10)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
		store.setSubset(12)
		expect(get(store)).toEqual({ index: 0, value: 1, start: 0, end: 9 })
	})
})
