import { describe, it, expect } from 'vitest'
// skipcq: JS-C1003 - Importing all components for verification
import * as functions from '../src/index.js'

describe('@rokkit/core', () => {
	it('should contain all exported functions', () => {
		// Sorted: the set of names is the API. A real ESM namespace orders its keys by name
		// anyway; vitest's transform lists them in declaration order, which a module split moves.
		expect(Object.keys(functions).sort()).toEqual(
			[
			'ColorSpace',
			'relativeLuminance',
			'FieldMapper',
			'getItemAtIndex',
			'getIndexForItem',
			'createEmitter',
			'getLineTypes',
			'weekdays',
			'getCalendarDays',
			'generateTicks',
			'getNestedFields',
			'defaultColors',
			'syntaxColors',
			'shades',
			'defaultPalette',
			'categoricalPalette',
			'categoricalFamilies',
			'DATA_IMAGE_REGEX',
			'ITEM_SNIPPET',
			'GROUP_SNIPPET',
			'DEFAULT_FIELDS',
			'BASE_FIELDS',
			'DEFAULT_ICONS',
			'DEFAULT_OPTIONS',
			'DEFAULT_KEYMAP',
			'DEFAULT_THEME_MAPPING',
			'INVERTED_ROLES',
			'stateIconsFromNames',
			'DEFAULT_STATE_ICONS',
			'NAMED_TOKENS',
			'NAMED_TOKEN_SHADE_MAP',
			'NAMED_TOKEN_ROLE_MAP',
			'hasSoftCompanion',
			'shadeForNamedToken',
			'roleForNamedToken',
			'detectDirection',
			'isRTL',
			'getClosestAncestorWithAttribute',
			'noop',
			'id',
			'isObject',
			'toString',
			'iconShortcuts',
			'scaledPath',
			'getKeyFromPath',
			'getPathFromKey',
			'getSnippet',
			'resolveSnippet',
			'hex2rgb',
			'hex2oklch',
			'oklch2hex',
			'isIconClass',
			'getImage',
			'flattenNestedList',
			'toInitCapCase',
			'toPascalCase',
			'toHyphenCase',
			'compareStrings',
			'sortByParts',
			'uniqueId',
			'compact',
			'toHexString',
			'shadesOf',
			'themeRules',
			'contrastShortcuts',
			'ON_COLOR_DARK',
			'ON_COLOR_LIGHT',
			'ON_COLOR_Y_CROSSOVER',
			'pickOnColor',
			'Theme'
		].sort())
	})
})
