import { describe, it, expect } from 'vitest'
import * as utilities from '../src'

describe('utilities', () => {
	it('should contain all exported utilities', () => {
		expect(Object.keys(utilities)).toEqual([
			'defaultColors',
			'syntaxColors',
			'defaultFields',
			'defaultIcons',
			'defaultOptions',
			'defaultKeyMap',
			'defaultThemeMapping',
			'stateIconsFromNames',
			'defaultStateIcons',
			'flattenNestedList',
			'findValueFromPath',
			'getComponent',
			'getIcon',
			'getValue',
			'getText',
			'getAttribute',
			'hasChildren',
			'isExpanded',
			'isNested',
			'findItemByValue',
			'findItemByIndexArray',
			'findNearestItemBefore',
			'findLastVisibleChild',
			'findNearestItemAfter',
			'mappedList',
			'getLineTypes',
			'generateTicks',
			'weekdays',
			'getCalendarDays',
			'id',
			'isObject',
			'shadesOf',
			'stateColors',
			'themeColors',
			'iconShortcuts',
			'scaledPath',
			'themeRules',
			'getRegex',
			'parseFilters',
			'toInitCapCase',
			'toPascalCase',
			'toHyphenCase',
			'sortByParts',
			'compareStrings',
			'uniqueId',
			'compact',
			'toHexString'
		])
	})
})
