// Individual Icons
export { default as AcademicCap } from './AcademicCap.svelte'
export { default as Adjustments } from './Adjustments.svelte'
export { default as Annotation } from './Annotation.svelte'
// export { default as Heart } from './Heart.svelte'
// export { default as Login } from './Login.svelte'
// export { default as Logout } from './Logout.svelte'
// export { default as Upload } from './Upload.svelte'
// export { default as HashTag } from './HashTag.svelte'
// export { default as Sparkles } from './Sparkles.svelte'
// export { default as BookMark } from './BookMark.svelte'
// export { default as BloodGroup } from './BloodGroup.svelte'
// export { default as Categories } from './Categories.svelte'
// export { default as ChevronRight } from './ChevronRight.svelte'
// export { default as ChevronLeft } from './ChevronLeft.svelte'
// export { default as ChevronDown } from './ChevronDown.svelte'
// export { default as ChevronUp } from './ChevronUp.svelte'
// export { default as ChevronDoubleRight } from './ChevronDoubleRight.svelte'
// export { default as ChevronDoubleLeft } from './ChevronDoubleLeft.svelte'
// export { default as FingerPrint } from './FingerPrint.svelte'
// export { default as ColorSwatch } from './ColorSwatch.svelte'

// export { default as TrendingUp } from './TrendingUp.svelte'
// export { default as Dashboard } from './Dashboard.svelte'
// export { default as Filter } from './Filter.svelte'
// export { default as Delete } from './Delete.svelte'
// export { default as Note } from './Note.svelte'
// export { default as Identification } from './Identification.svelte'
// export { default as Certificate } from './Certificate.svelte'
// export { default as UserGroup } from './UserGroup.svelte'
// export { default as CrossCircle } from './CrossCircle.svelte'
