import { defineConfig } from 'unocss'
import { presetRokkit } from '@rokkit/unocss'
import config from './rokkit.config.js'

const siteIcons = [
	// i-solar icons
	'i-solar:add-circle-bold-duotone',
	'i-solar:alt-arrow-down-bold-duotone',
	'i-solar:alt-arrow-up-bold-duotone',
	'i-solar:arrow-left-bold-duotone',
	'i-solar:atom-bold-duotone',
	'i-solar:bell-bold-duotone',
	'i-solar:book-2-bold-duotone',
	'i-solar:calendar-bold-duotone',
	'i-solar:card-bold-duotone',
	'i-solar:chart-2-bold-duotone',
	'i-solar:chart-bold-duotone',
	'i-solar:chart-square-bold-duotone',
	'i-solar:chat-square-code-bold-duotone',
	'i-solar:check-circle-bold-duotone',
	'i-solar:checklist-minimalistic-bold-duotone',
	'i-solar:clock-circle-bold-duotone',
	'i-solar:close-circle-bold-duotone',
	'i-solar:code-bold-duotone',
	'i-solar:code-square-bold-duotone',
	'i-solar:cursor-bold-duotone',
	'i-solar:database-bold-duotone',
	'i-solar:eye-bold-duotone',
	'i-solar:file-text-bold-duotone',
	'i-solar:flag-bold-duotone',
	'i-solar:folder-open-bold-duotone',
	'i-solar:gallery-wide-bold-duotone',
	'i-solar:gamepad-bold-duotone',
	'i-solar:git-merge-bold-duotone',
	'i-solar:graph-new-bold-duotone',
	'i-solar:hamburger-menu-bold-duotone',
	'i-solar:home-bold-duotone',
	'i-solar:hourglass-bold-duotone',
	'i-solar:keyboard-bold-duotone',
	'i-solar:layers-bold-duotone',
	'i-solar:layers-minimalistic-bold-duotone',
	'i-solar:list-check-bold-duotone',
	'i-solar:magic-stick-bold-duotone',
	'i-solar:magnifer-bold-duotone',
	'i-solar:minimize-square-bold-duotone',
	'i-solar:minus-circle-bold-duotone',
	'i-solar:palette-bold-duotone',
	'i-solar:rocket-bold-duotone',
	'i-solar:settings-bold-duotone',
	'i-solar:shield-bold-duotone',
	'i-solar:sidebar-bold-duotone',
	'i-solar:table-bold-duotone',
	'i-solar:user-bold-duotone',
	'i-solar:users-group-two-rounded-bold-duotone',
	'i-solar:widget-bold-duotone',
	// i-lucide icons
	'i-lucide:activity',
	'i-lucide:align-center',
	'i-lucide:align-left',
	'i-lucide:align-right',
	'i-lucide:apple',
	'i-lucide:banana',
	'i-lucide:bar-chart-2',
	'i-lucide:bell',
	'i-lucide:blocks',
	'i-lucide:bold',
	'i-lucide:book-open',
	'i-lucide:box',
	'i-lucide:calendar',
	'i-lucide:calendar-range',
	'i-lucide:carrot',
	'i-lucide:cherry',
	'i-lucide:chevron-down',
	'i-lucide:chevron-right',
	'i-lucide:circle',
	'i-lucide:clipboard',
	'i-lucide:cloud-upload',
	'i-lucide:code-2',
	'i-lucide:copy',
	'i-lucide:credit-card',
	'i-lucide:diamond',
	'i-lucide:download',
	'i-lucide:edit',
	'i-lucide:file',
	'i-lucide:file-code',
	'i-lucide:file-text',
	'i-lucide:flask-conical',
	'i-lucide:folder',
	'i-lucide:folder-open',
	'i-lucide:form-input',
	'i-lucide:globe',
	'i-lucide:heart',
	'i-lucide:home',
	'i-lucide:image',
	'i-lucide:inbox',
	'i-lucide:info',
	'i-lucide:italic',
	'i-lucide:layers',
	'i-lucide:layout-dashboard',
	'i-lucide:layout-grid',
	'i-lucide:layout-list',
	'i-lucide:leaf',
	'i-lucide:lock',
	'i-lucide:mail',
	'i-lucide:menu',
	'i-lucide:monitor',
	'i-lucide:moon',
	'i-lucide:mouse-pointer-click',
	'i-lucide:package',
	'i-lucide:palette',
	'i-lucide:play',
	'i-lucide:plus',
	'i-lucide:rocket',
	'i-lucide:rotate-ccw',
	'i-lucide:save',
	'i-lucide:scissors',
	'i-lucide:send',
	'i-lucide:settings',
	'i-lucide:share',
	'i-lucide:slash',
	'i-lucide:star',
	'i-lucide:sun',
	'i-lucide:tag',
	'i-lucide:trash',
	'i-lucide:trash-2',
	'i-lucide:underline',
	'i-lucide:upload',
	'i-lucide:user',
	'i-lucide:wheat',
	'i-lucide:zap'
]

const componentIcons = [
	'accordion',
	'button',
	'card',
	'calendar',
	'carousel',
	'checkbox',
	'combobox',
	'crumbs',
	'dropdown',
	'icon',
	'input-text',
	'item',
	'list',
	'message',
	'palette',
	'pill',
	'progress',
	'range',
	'multiselect',
	'select',
	'settings',
	'stepper',
	'switch',
	'tabs',
	'table',
	'tree',
	'radio',
	'rating',
	'input-password'
].map((icon) => `i-component:${icon}`)

export default defineConfig({
	presets: [presetRokkit(config)],
	shortcuts: [
		['text-on-primary', 'text-surface-50'],
		['text-on-secondary', 'text-surface-50'],
		['text-on-info', 'text-surface-50'],
		['text-on-success', 'text-surface-50'],
		['text-on-warning', 'text-surface-50'],
		['text-on-error', 'text-surface-50'],
		['text-on-surface', 'text-surface-50']
	],
	safelist: [...siteIcons, ...componentIcons],
	content: {
		pipeline: {
			include: [
				'src/**/*.{svelte,js,ts}',
				'../../packages/themes/src/**/*.css',
				'../../packages/ui/src/**/*.svelte'
			]
		}
	}
})
