name: codecov-reporter

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    name: codecov-reporter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        pnpm-version: [7.x]
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: |
          ./packages/base/coverage/lcov.info,
          ./packages/chart/coverage/lcov.info,
          ./packages/icons/coverage/lcov.info,
          ./packages/list/coverage/lcov.info
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)