name: Coverage

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  analyze:
    name: code-climate-reporter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [8.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Intall pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm i
        env:
          NODE_OPTIONS: '--max_old_space_size=6144'
      # - name: Run tests
      #   run: pnpm test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageCommand: pnpm coverage:lcov
          debug: true
          coverageLocations: lcov.info:lcov
