name: Release
on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
jobs:
  sentry:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.email "me@jerrythomas.name"
          git config --global user.name "Jerry Thomas"
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          pnpm release
