import { describe, it, expect } from 'vitest'
// skipcq: JS-C1003 - Importing all components for verification
import * as functions from '../src/index.js'

describe('@rokkit/core', () => {
	it('should contain all exported functions', () => {
		expect(Object.keys(functions)).toEqual([
			'FieldMapper',
			'getItemAtIndex',
			'getIndexForItem',
			'createEmitter',
			'getLineTypes',
			'weekdays',
			'getCalendarDays',
			'generateTicks',
			'getValue',
			'getNestedFields',
			'hasChildren',
			'isExpanded',
			'defaultColors',
			'syntaxColors',
			'shades',
			'defaultPalette',
			'DATA_IMAGE_REGEX',
			'ITEM_SNIPPET',
			'GROUP_SNIPPET',
			'DEFAULT_FIELDS',
			'DEFAULT_ICONS',
			'DEFAULT_OPTIONS',
			'DEFAULT_KEYMAP',
			'DEFAULT_THEME_MAPPING',
			'TONE_MAP',
			'stateIconsFromNames',
			'DEFAULT_STATE_ICONS',
			'detectDirection',
			'isRTL',
			'getClosestAncestorWithAttribute',
			'noop',
			'id',
			'isObject',
			'toString',
			'iconShortcuts',
			'scaledPath',
			'getKeyFromPath',
			'getPathFromKey',
			'getSnippet',
			'resolveSnippet',
			'hex2rgb',
			'getImage',
			'flattenNestedList',
			'findValueFromPath',
			'toInitCapCase',
			'toPascalCase',
			'toHyphenCase',
			'compareStrings',
			'sortByParts',
			'uniqueId',
			'compact',
			'toHexString',
			'shadesOf',
			'themeRules',
			'semanticShortcuts',
			'contrastShortcuts',
			'Theme'
		])
	})
})
